### PR TITLE
Smooth player movement, bug fix, refactoring

### LINKED ISSUE #26: Player movement
- [x] Add arrow keys as movement option
- [ ] Make movement smooth
- [ ] Prevent unintended actions

### PR DESCRIPTION
**Pull request by maxmeijer42**
* Player now moves smoothly
* Fix bug where stopping is detected too late
* Split game logic from rendering logic

Should close #26

### CODE REVIEW

File: MeesGame/Gameplay/GameObjects/Player.cs [hunk 1]
```diff
@@ -108,22 +108,85 @@ public void PerformAction(PlayerAction action)
...
+                    return new Vector2(-1, 0);
+            }
+            return new Vector2(0, 0);
+        }
+
+        private float Speed
+        {
+            get
+            {
+                return (float)(level.Tiles.CellHeight / level.TimeBetweenActions.TotalSeconds);
```
Comment (jensj12) [inline MeesGame/Gameplay/GameObjects/Player.cs:181]: Should be converted to float before division

**Review by jensj12 — CHANGES_REQUESTED** [review]

File: MeesGame/Gameplay/GameObjects/Player.cs (hunk 1 above)
Comment (maxmeijer42) [reply MeesGame/Gameplay/GameObjects/Player.cs:181]: Nice catch!

Comment (maxmeijer42) [reply MeesGame/Gameplay/GameObjects/Player.cs:181]: Oh eigenlijk maakt het niet uit want TotalSeconds is een double

Comment (jensj12) [reply MeesGame/Gameplay/GameObjects/Player.cs:181]: If the code looks like a bug, it is a bug. Convert it before division or not at all.

Comment (maxmeijer42) [reply MeesGame/Gameplay/GameObjects/Player.cs:181]: > Convert it before division or not at all.

The reason it is cast after the division, is that otherwise it would be a double. So we're not casting from int to float but from double to float. Doing the casting before the division would still make it a double division. So if we do the casting before the division we would need to cast twice and the cast before division would be redundant.

Comment (jensj12) [reply MeesGame/Gameplay/GameObjects/Player.cs:181]: It seems operator/ already converts the left hand side to a double if the right hand side is a double. I'll mark this as resolved.

**Review by jensj12 — APPROVED** [review]

**Review by jensj12 — CHANGES_REQUESTED** [review]
Undo the merge with the non-master branches and rebase

**Comment by jensj12** [comment]
Still contains delete TileFieldView. When rebasing, use `git rebase master -i` and follow instructions to drop certain commits (and squash stuff if needed).

**Comment by maxmeijer42** [comment]
Yeah it intentionally contains delete-tile-field-view. I closed the pull request concerning that and included it here. Saves us from having to do another merge.

**Comment by jensj12** [comment]
You already put it in PR #35 (which seemed more logical to me).

**Comment by maxmeijer42** [comment]
Oh, right

**Comment by maxmeijer42** [comment]
Rebased

**Review by jensj12 — APPROVED** [review]
